### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jtpio** [martinRenou/jupyterlite-sphinx#1]
Thanks @martinRenou for starting this.

Maybe we would like to start publishing this package to PyPI, and see if we can integrate it with existing repos.

I pushed a placeholder to https://pypi.org/project/jupyterlite-sphinx/, let me know if you would like to be added to it. Thanks!

**Comment by martinRenou** [comment]
Sure we can do this :)

I'll invite you to have full rights on this repo. I guess it's a bit early to make it part of the jupyterlite org but it's up to you.

**Comment by martinRenou** [comment]
It can be found here https://pypi.org/project/jupyterlite-sphinx/0.1.0, it's a very minimal first version

**Comment by jtpio** [comment]
Nice thanks, a good start!
